### ISSUE TITLE
Minor Bugs

### ISSUE THREAD

**Issue by GustavooCruz** [steve4744/TNTRun#89] opened 2022-03-09 05:15 UTC
There are 3 minor bugs on TNT Run plugin. They were already happening before the 9.18 update so it's not an update issue.

**1st Bug:** _When you die in PVP Combat, you lose your fly perms as a spectator for the rest of the game (easily testable playing with 3 players and very noticeable)._

**2nd Bug:** _The moment when the fireworks are rolling (the ending of the game) for some reason you can still use the double jumps that you have left, also very noticeable and annoying sometimes._

**3rd Bug:** _This one doesn't annoy me that much because I learned to deal with, but it's still a bug. So when you set the arena spawn location or the spectator spawn location no matter where you are looking at when you set the spawn, you will always spawn in-game looking at the south and not direction that you set it originally. Altering it through files also seems impossible without giving error and the arena not recognizing the spawn anymore. I've tried._

**Comment by steve4744** [comment] 2022-03-10 11:40
1) this has been fixed in 244a9ea

2) this only affected the winner but has been fixed in d902bbb

3) technically not a bug as saving the pitch and yaw is a feature that was only implemented when setting the global lobby. Altering the files doesn't help because this feature is not implemented for the spawn points.

Note that this feature was added for the spectator spawn in version 9.17 in commit 38733b6

**Closed** 2022-03-12 11:52 UTC
